### ISSUE TITLE
Temp folder can't be accessed sometimes

### ISSUE THREAD

**Issue by opusforlife2** [eibol/ffmpeg_batch#34]
I get this exception sometimes when the program is about to start converting files. Then I have to run the program as admin to be able to avoid the error.

```
************** Exception Text **************
System.UnauthorizedAccessException: Access to the path 'C:\Users\<username>\AppData\Local\Temp\FFBatch_test' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path)
   at FFBatch.Form1.btn_multi_m_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.PerformClick()
   at FFBatch.Form1.BG_Try_preset_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
```

**Comment by eibol** [comment]
Thanks, I've found the probable cause. You could test it using this [patched executable](https://drive.upm.es/s/NJ13WkGf9htZ9do/download).

**Comment by opusforlife2** [comment]
Hi. Same error with the linked executable.

**Comment by eibol** [comment]
You could you try disabling "Try Preset" for the moment. I'll continue searching for a cause.

**Comment by opusforlife2** [comment]
Ah. The `Don't try preset` checkbox. Alright. I'll use that as a workaround. Thanks.

**Comment by eibol** [comment]
New [patched exe](https://drive.upm.es/s/NJ13WkGf9htZ9do/download) for testing purposes.

**Comment by opusforlife2** [comment]
I tried a few different sets of files with the new executable and haven't encountered the error again so far. So that's a tentative yes on the fix. 🎉
